Add isolation to tests and comment tests affected by io isolation
ballerina-platform/module-ballerina-socket pull request #67
Opened 2020-10-27 17:24 UTC by Maninda

## Purpose
Resolve isolation related to tests and comment out the tests affected by non-isolated _io_ methods.

2020-11-03 06:32 UTC, BuddhiWathsala requested changes

2020-11-03 06:32 UTC, BuddhiWathsala commented on gradle.properties
>  stdlibLogVersion=1.0.1-SNAPSHOT
```suggestion
stdlibLogVersion=1.0.2-SNAPSHOT
```

2020-11-03 06:35 UTC, BuddhiWathsala approved these changes
LGTM

2020-11-03 06:55 UTC, merged

2020-11-05 07:18 UTC, ThisaruGuruge commented on gradle.properties
> +version=0.7.0-SNAPSHOT
Why are we bumping a minor version here? This should be `0.6.10-SNAPSHOT` right?